### ISSUE TITLE
typescript definition for __Rewire__ doesn't exist

### ISSUE THREAD

**Issue by bloody-ux** [rosswarren/babel-plugin-rewire-ts#12]
It's a really good plugin for testing, but I have a problem: rewire helper functions do not have definitions

![image](https://user-images.githubusercontent.com/19991767/94355988-e2452a00-00bb-11eb-8cbd-b37c9f27863f.png)

**Comment by priyank-p** [comment]
I have two questions:
- Do you get this error when running the code? I am pretty sure it's just the vscode intellisense and not an actual runtime error. 
- Are you writing your test code in TypeScript? If so you should just write them as in regular JS.

**Comment by bloody-ux** [comment]
- "Do you get this error when running the code? I am pretty sure it's just the vscode intellisense and not an actual runtime error."

It can run correctly but always a ts error on vscode.

- "Are you writing your test code in TypeScript? If so you should just write them as in regular JS."

Yes, we write test code in TypeScript.

**Comment by priyank-p** [comment]
OK, the problem here is that your write your test code in TypeScript. There is really no easy way (it may even be impossible) to make TypeScript aware of rewire adding `__Rewire__` and such on top of an imported module. 

I suggest writing the test code in plain JS.

**Comment by priyank-p** [comment]
Closing this as a "wontfix" since this isn't really something we can fix.
